application: phpbeginner-142910
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /(.+\.(html|css|js|gif|png|jpg))$
  static_files: \1
  upload: .+\.(html|css|js|gif|png|jpg)$
  application_readable: true

# PHP Scriptbestanden.


- url: /css
  static_dir: css

- url: /form.php
  script: form.php

- url: /.*
  script: header.php

- url: /(.+\.php)$
  script: \1